server:
  port: 8081

spring:
  application:
    name: rabbit
  # cloud:
  #   config:
  #     uri: http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka