server:
  port: 8080

jwt:
  secret: usersecret

spring:
  application:
    name: auth
  redis:
    host: localhost
    port: 6379
  # cloud:
  #   config:
  #     uri: http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka